services:
  - type: web
    env: python
    buildCommand: cd proyecto-fullstack/backend && pip install -r requirements.txt
    startCommand: cd proyecto-fullstack/backend && python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings